# Numpy Tutorial
Numpy is a linear algebra / scientific computing library for Python. The implimentation is written in C, so its super fast! Numpy is the backbone of the python scientific computing / machine learning. Whats more, the concepts you learn here will extend to more advanced libraries like tensor flow. We will use numpy extensively in this class, so heres a tutorial. The sections labeled "TODO" are for you to fill in.

## Basics

From numpy's [site](https://docs.scipy.org/doc/numpy/user/quickstart.html):

"NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes.

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3."

![](https://i.stack.imgur.com/DL0iQ.jpg)





In [1]:
# This imports all of numpy's functionality under the name "np"
import numpy as np

# Create a 2x3
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
# The dimensions of the array are called the "shape"
x.shape

(2, 3)

In [3]:
# You can also get the total number of elements the array contains, regarless of shape
x.size

6

In [4]:
# And you can see what type of data the array contains
x.dtype

dtype('int64')

## TODO

In [5]:
# Create an array with a shape of (3,)

# Create an array with a shape of (3, 3, 1)

## Indexing and Slicing
Numpy has its own syntax for indexing elements of an array. With it you can retrieve individual elements or subsections of the array called "slices"

In [6]:
# Here is what x looks like for reference
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Get the top left element
x[0,0]

1

In [8]:
# Get the top right element
x[0,2]

3

In [9]:
# Get the second row
x[1,:] # just x[1] also works

array([4, 5, 6])

In [10]:
# Get the first column
x[:,0] # in this case you must use the ':'

array([1, 4])

In [11]:
# Get the last two elements of the second row
x[1,1:3] # this is a "slice"

array([5, 6])

In [12]:
# Since this slice goes to the end you can also leave off the 3 and say 
x[1,1:] # leaving off the second number in the slice means "go to the end"

array([5, 6])

In [13]:
# If you leave off the fist number in the slice it means "start from the beginning"
x[1,:2] # the first two elements of the second row

array([4, 5])

In [14]:
x = np.arange(100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
# Get every 3rd element from 10 to 30
x[10:31:3]

array([10, 13, 16, 19, 22, 25, 28])

In [16]:
# Get every 2nd element
x[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [17]:
# Get every element greater than 40
x[x>40]

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
       75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
       92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
# This works because numpy also accepts a boolean mask as an index for example
x = np.array([1,2,3])
mask = [True, True, False] # Select the first and second element, but not the last
x[mask]

array([1, 2])

In [19]:
# this expresion generates a boolean mask
x == 2

array([False,  True, False])

In [20]:
# Which you can then use to select elements
x[x==2]

array([2])

## TODO

In [21]:
# Here is what x looks like for reference
x = np.arange(25).reshape((5,5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
# print the center 3x3 square of x

# print every other row of x

# print every other column of x

# print every perfect square in x (Using boolean masks. Don't write the boolean mask explicitly)


## Manipulating Arrays
The shape of an array can be changed after its been created and you can combine different arrays together

In [23]:
x = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [24]:
# You can take an array with any shape and turn it into a normal list with
x.flatten() # Note this does not change x, but returns a flat copy of x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
# You can also reshape the an array with
x.reshape(3,4) # Note this does not change x, but returns a reshaped copy of x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
# Add a column to x
y = np.array([[99],[99]]) 
# notice that y is not the same as np.array([99, 99]). We create y this way to give it the shape (2, 1)
# so that it matches the shape of x (2, 6)
np.concatenate((x, y), axis=1) # again, this returns a modified copy. 

array([[ 0,  1,  2,  3,  4,  5, 99],
       [ 6,  7,  8,  9, 10, 11, 99]])

In [27]:
# Add a row to x
y = np.array([[99,99,99,99,99,99]])
np.concatenate((x, y), axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [99, 99, 99, 99, 99, 99]])

## TODO

In [28]:
# Concatenate x, y and z to form a 4 x 3 matrix
x = np.array([[1], [2], [3], [4]])
y = np.array([[5], [6], [7], [8]])
z = np.array([[9], [10], [11], [12]])

## Useful Functions

In [29]:
# As you've seen above arange can be used to create a sequence
np.arange(1, 10, 3) # start from one, up to but not including 10, in with a step size of 3

array([1, 4, 7])

In [30]:
# fill the specified array shape with zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
# the same thing but with ones
np.ones(4)

array([1., 1., 1., 1.])

In [32]:
x = np.ones((3,4))
# Find the sum of an entire array. 
np.sum(x)
# This is much faster than normal python, since the implementation is in C

12.0

In [33]:
# Sum each column column individually
np.sum(x, axis=0)

array([3., 3., 3., 3.])

In [34]:
# Find the global max of x
np.max(x)

1.0

In [35]:
# find the max of each row of x
np.max(x, axis=1)

array([1., 1., 1.])

In [36]:
x = np.array([[8,1,7], [4,3,9], [5,2,6]])
print(x)

[[8 1 7]
 [4 3 9]
 [5 2 6]]


In [37]:
# Sort each column of x. If you're not familiar with python, sorted is a built in function
# you can pass in any function youb want here
np.apply_along_axis(sorted, 0, x)

array([[4, 1, 6],
       [5, 2, 7],
       [8, 3, 9]])

## TODO

In [38]:
# Answer all questions using the above functions
# Find the sum odd every odd number from 123 to 257

# Generate a flat array where each entry is a boolean representing
# if there is a 3 in the corresponding row of x. The ouput should be 
# array([False, False, True])
x = np.array([[1,4,5], [8, 8, 7], [2,4,3]])

# Find the sum of the maxes of each column in x



## Math / Linear algebra

In [39]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [40]:
# Find the transpose
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [41]:
# add a constant to each element
x + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# add corresponding elements
x + x

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [43]:
# Mulitply every element by 5
x * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [44]:
# Mulitply corresponding elements
x * x

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [45]:
# Perform matrix multiplication
x.dot(x)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

## By now I think you've got it, so no more TODOs!
There are many more features and functions that numpy has to offer, you can explore them at http://www.numpy.org/